<?php

function getAutoGeneratedEmployeeID() {

    $Database = new Database;

    $query = "SELECT MAX(`ID`) AS `ID` FROM `employee`";
    
    $stmt = $Database->connect()->prepare($query);

    if(!$stmt->execute()) {
        header("Location: ../views/employees.view/employee.php?error");
        $stmt = null;
        die();
    }

    $result = $stmt->fetch();
    return $result['ID'];
}