<?php

// na initialize na daan sa inventory.inc.php.

function getAutoGeneratedItemNo() {

    $Database = new Database;

    $query = "SELECT MAX(`ID`) AS `ID` FROM `inventory`";

    $stmt = $Database->connect()->prepare($query);

    if(!$stmt->execute()) {
        header("Location: ../views/inventory.view/inventory.php?error");
        $stmt=null;
        die();
    }

    $maxID = $stmt->fetch();

    return $maxID['ID'];
}