<?php

// na initialize na daan sa inventory.inc.php.

function getAutoGeneratedSalesID()
{

    $Database = new Database;

    $query = "SELECT MAX(`ID`) AS `ID` FROM `sales`";

    $stmt = $Database->connect()->prepare($query);

    if (!$stmt->execute()) {
        header("Location: ../views/sales.view/sales.php?error");
        $stmt = null;
        die();
    }

    $maxID = $stmt->fetch();

    return $maxID['ID'];
}
